services:
  app:
    build:
      context: ./docker/php
    container_name: laravel_app
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel_red_2025
      - shared_network

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_red_2025

  node:
    image: node:22
    container_name: laravel_node
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    networks:
      - laravel_red_2025

  composer:
    build:
      context: ./docker/php
    container_name: laravel_composer
    working_dir: /var/www
    volumes:
      - .:/var/www
    entrypoint: ["composer"]
    networks:
      - laravel_red_2025

networks:
  laravel_red_2025:
    driver: bridge
  shared_network:
    external: true