name: Deploy Administrado-Zuma
on:
  push:
    branches:
      - main

jobs:
  deploy-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH client
        run: sudo apt-get install openssh-client -y

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          envs: "DOCKER_IMAGE_TAG=latest"
          script: |
            cd zuma/services/zuma-admin || exit 1

            # Pull de la imagen más reciente
            docker pull ghcr.io/adm-garantiacapital/garantia-fondeo:$DOCKER_IMAGE_TAG

            # Detener y eliminar contenedor antiguo
            docker compose stop zuma-adm || true
            docker compose rm -f zuma-adm || true

            # Eliminar imagen antigua
            docker image rm ghcr.io/adm-garantiacapital/garantia-fondeo:$DOCKER_IMAGE_TAG || true

            # Levantar contenedor
            docker compose up -d zuma-adm

            # Ejecutar setup.sh
            sh setup.sh
