name: CI/CD Zuma Admin

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # 1. Checkout del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Login a GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. Build y push de la imagen Docker
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./services/zuma-admin
          file: ./services/zuma-admin/docker/php/Dockerfile
          push: true
          tags: ghcr.io/adm-garantiacapital/administrado-zuma:latest
          build-args: |
            APP_NAME=Laravel
            APP_ENV=production
            APP_KEY=${{ secrets.APP_KEY }}
            APP_DEBUG=false
            APP_TIMEZONE=UTC
            APP_URL=https://admin.zuma.com.pe
            CLIENT_APP_URL=https://admin.zuma.com.pe
            RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
            BREVO_KEY=${{ secrets.BREVO_KEY }}
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            CONSULTA_DNI_API_TOKEN=${{ secrets.CONSULTA_DNI_API_TOKEN }}
            CONSULTA_RUC_API_TOKEN=${{ secrets.CONSULTA_RUC_API_TOKEN }}
            TWILIO_SID=${{ secrets.TWILIO_SID }}
            TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }}
            TWILIO_WHATSAPP_FROM=${{ secrets.TWILIO_WHATSAPP_FROM }}

      # 5. Opcional: SSH deploy a tu servidor
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /var/www/zuma-admin
            docker compose pull zuma-adm
            docker compose up -d zuma-adm
            echo "✅ Deploy completado"
